apiVersion: apps/v1
kind: Deployment
metadata:
  name: avia-search
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avia-search
  template:
    metadata:
      labels:
        app: avia-search
    spec:
      containers:
      - name: avia-search
        image: viktor1cod/avia-search:44f733fcf4eb9d13b8f49f04845c7920c20ce356
        ports:
        - containerPort: 80
