apiVersion: apps/v1
kind: Deployment
metadata:
  name: avia-search
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avia-search
  template:
    metadata:
      labels:
        app: avia-search
    spec:
      containers:
      - name: avia-search
        image: viktor1cod/avia-search:a639e0ed459ad8798389029c5c3507784fd29f26
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
