apiVersion: apps/v1
kind: Deployment
metadata:
  name: avia-search
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avia-search
  template:
    metadata:
      labels:
        app: avia-search
    spec:
      containers:
      - name: avia-search
        image: viktor1cod/avia-search:8797c9bd054fb3a324201e6973a30b8059a4d0c8
        ports:
        - containerPort: 80
